#These are defaults that will be used when no value is given in a per-world config.
Default:
  World:
    #How many ticks are between each teleport check? Lowering this increases server load but makes teleporting smoother
    DelayedTicks: 2
    #Should we predict entity positions? This will make teleporting a bit smoother, but can cause early unwanted teleportation. Predicted positions are <DelayedTicks> ahead of the current situation.
    DoPredictPosition: true
  Upper:
    #What world should climbing go to? (null or unknown world to disable climbing)
    World: null
    #On what layer should the overlapping start?
    OverlapStart: 255
    #On what layer should the overlapping start in the targeted world?
    OverlapTarget: 0
    #How many layers should we copy into this world from the above world?
    Overlap: 0
    #At what layer should we teleport entities and players?
    Teleport: 255
    #To what layer should we teleport entities and players?
    TeleportTarget: 1
    #Should we preserve velocity?
    PreserveEntityVelocity: true
    #Should we preserve distance fallen?
    PreserveEntityFallDistance: true
    #Set the entities you want to don't want to allow to true
    EntityFilter:
      #Normal entities
      Item: false
      XPOrb: false
      Painting: true
      Arrow: false
      Snowball: false
      Fireball: false
      SmallFireball: false
      ThrownEnderpearl: false
      EyeOfEnderSignal: false
      ThrownEXpBottle: false
      PrimedTnt: false
      FallingSand: false
      Minecart: false
      Boat: false
      #NPCs - Aggressive
      Creeper: false
      Skeleton: false
      Spider: false
      Giant: false
      Zombie: false
      Slime: false
      Ghast: false
      PigZombie: false
      Enderman: false
      CaveSpider: false
      Silverfish: false
      Blaze: false
      LavaSlime: false
      EnderDragon: true
      #NPCs - Passive
      Pig: false
      Sheep: false
      Cow: false
      Chicken: false
      Squid: false
      Wolf: false
      MushroomCow: false
      SnowMan: false
      Ozelot: false
      VillagerGolem: false
      Villager: false
  Lower:
    #What world should falling go to? (null or unknown world to disable falling)
    World: null
    #On what layer should the overlapping start?
    OverlapStart: 0
    #On what layer should the overlapping start in the targeted world?
    OverlapTarget: 255
    #How many layers should we copy into this world from the above world?
    Overlap: 0
    #At what layer should we teleport entities and players?
    Teleport: 0
    #To what layer should we teleport entities and players?
    TeleportTarget: 254
    #Should we preserve velocity?
    PreserveEntityVelocity: true
    #Should we preserve distance fallen?
    PreserveEntityFallDistance: true
    #Set the entities you want to don't want to allow to true
    EntityFilter:
      #Normal entities
      Item: false
      XPOrb: false
      Painting: true
      Arrow: false
      Snowball: false
      Fireball: false
      SmallFireball: false
      ThrownEnderpearl: false
      EyeOfEnderSignal: false
      ThrownEXpBottle: false
      PrimedTnt: false
      FallingSand: false
      Minecart: false
      Boat: false
      #NPCs - Aggressive
      Creeper: false
      Skeleton: false
      Spider: false
      Giant: false
      Zombie: false
      Slime: false
      Ghast: false
      PigZombie: false
      Enderman: false
      CaveSpider: false
      Silverfish: false
      Blaze: false
      LavaSlime: false
      EnderDragon: true
      #NPCs - Passive
      Pig: false
      Sheep: false
      Cow: false
      Chicken: false
      Squid: false
      Wolf: false
      MushroomCow: false
      SnowMan: false
      Ozelot: false
      VillagerGolem: false
      Villager: false