upper:
  #What world should climbing go to? (null or unknown world to disable climbing)
  world: null
  #What layer should the overlapping take blocks & events from?
  overlapstart: 0
  #How many layers should we copy into this world from the above world?
  overlap: 0
  #At what layer should we teleport entities and players?
  teleport: 255
  #To what layer should we teleport entities and players?
  teleporttarget: 1
lower:
  #What world should falling go to? (null or unknown world to disable falling)
  world: null
  #What layer should the overlapping take blocks & events from?
  overlapstart: 255
  #How many layers should we copy into this world from the below world?
  overlap: 0
  #At what layer should we teleport entities and players?
  teleport: 0
  #To what layer should we teleport entities and players?
  teleporttarget: 254