## Inception plugin.yml file
## no-modify {
name: Inception
version: 0.0.0
load: STARTUP
author: Xaymar
website: http://alteredgaming.de/
main: ag.AlteredGaming.Inception
## }
commands:
permissions: